baseURL = "https://www.bryanray.net/"
locale = "en-US"
title = "Bryan Ray"

canonifyurls = true
enableRobotsTXT = true

pygmentsstyle = "bw"
pygmentsUseClasses = true
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "bryanray"

[pagination]
pagerSize = 20

[taxonomies]
tag = "tags"

[permalinks]
posts = "/:year/:month/:slug"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Bryan Ray"
info = "Code, Projects & Life"
description = "A developer's notebook about software, personal projects, and the moments in between."
keywords = "blog,developer,software,projects,personal"
avatar = "images/bryanray-headshot.jpeg"

footercontent = "Built with ♥️"

hidecredits = false
hidecopyright = false

rtl = false

math = true

# Menu links
[[menu.main]]
name = "Notebook"
weight = 1
url = "/posts"
[[menu.main]]
name = "Bookshelf"
weight = 4
url = "/bookshelf"
[[menu.main]]
name = "About"
weight = 5
url = "/about"
